### ISSUE TITLE
Add Demo / Example

### ISSUE THREAD

**Issue by romellem** [romellogoodman/flow-field.js#1]
I played around with this a tiny bit and made a small demo

- https://codesandbox.io/s/flow-field-example-914pz

Feel free to copy the code and include in the repo, or if the demo doesn't showcase what the library is meant to do, feel free to create a new demo.

**Comment by romellogoodman** [comment]
Yo! Thanks so much for making this. I just added a codesandbox example to the readme that has a little bit more interactivity. Check it out!
